CREATE TABLE IF NOT EXISTS `attachments` (
  `ATTACHMENT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ATTACHMENT_CONTENT` longblob NOT NULL,
  `ATTACHMENT_NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ATTACHMENT_ID`),
  UNIQUE KEY `ATTACHMENT_ID` (`ATTACHMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `category` (
  `CATEGORY_ID` int(11) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`CATEGORY_ID`),
  UNIQUE KEY `CATEGORY_ID` (`CATEGORY_ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `CouponHistory` (
  `COUPON_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `OFFER_ID` bigint(20) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `COUPON_CODE` varchar(255) NOT NULL,
  `MOBILE_NUMBER` varchar(255) NOT NULL,
  PRIMARY KEY (`COUPON_ID`),
  UNIQUE KEY `COUPON_ID` (`COUPON_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=673 ;

CREATE TABLE IF NOT EXISTS `Coupons` (
  `COUPON_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COUPON_CODE` varchar(255) NOT NULL,
  `OFFER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`COUPON_ID`),
  UNIQUE KEY `COUPON_ID` (`COUPON_ID`),
  KEY `FK9C50C4EDC52C5CE6` (`OFFER_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=769 ;

CREATE TABLE IF NOT EXISTS `mail` (
  `MAIL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MAIL_BODY` tinyblob NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `FROM_MAIL_ID` varchar(255) NOT NULL,
  `STATUS` varchar(255) NOT NULL,
  `SUBJECT` varchar(255) NOT NULL,
  `TO_MAIL_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`MAIL_ID`),
  UNIQUE KEY `MAIL_ID` (`MAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `mail_attachments` (
  `mail_MAIL_ID` bigint(20) NOT NULL,
  `attachments_ATTACHMENT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`mail_MAIL_ID`,`attachments_ATTACHMENT_ID`),
  UNIQUE KEY `attachments_ATTACHMENT_ID` (`attachments_ATTACHMENT_ID`),
  KEY `FK95D55283138A864` (`attachments_ATTACHMENT_ID`),
  KEY `FK95D55285FA67619` (`mail_MAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Offer` (
  `OFFER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `START_DATE` datetime NOT NULL,
  `STATUS` varchar(255) NOT NULL,
  `END_DATE` datetime NOT NULL,
  `OFFER_NAME` varchar(255) NOT NULL,
  `PRICE` int(11) NOT NULL,
  `PRODUCTS` varchar(255) DEFAULT NULL,
  `DISCOUNT` int(11) NOT NULL,
  `COUPON_PRICE` int(11) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `COVER_IMAGE` varchar(255) NOT NULL,
  `COUPON_TYPE` varchar(255) NOT NULL,
  `COUPON_CODE_PROVIDER` varchar(255) NOT NULL,
  `PROVIDER_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`OFFER_ID`),
  UNIQUE KEY `OFFER_ID` (`OFFER_ID`),
  KEY `FK4892A3C7A9D0766` (`PROVIDER_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=20 ;


CREATE TABLE IF NOT EXISTS `offer_category` (
  `OFFER_ID` bigint(20) NOT NULL,
  `CATEGORY_ID` int(11) NOT NULL,
  PRIMARY KEY (`OFFER_ID`,`CATEGORY_ID`),
  KEY `FK977DBB81C52C5CE6` (`OFFER_ID`),
  KEY `FK977DBB81752D8E0C` (`CATEGORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Outlet` (
  `OUTLET_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AREA` varchar(255) NOT NULL,
  `OUTLET_NAME` varchar(255) NOT NULL,
  `CITY` varchar(255) NOT NULL,
  `PROVIDER_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`OUTLET_ID`),
  UNIQUE KEY `OUTLET_ID` (`OUTLET_ID`),
  UNIQUE KEY `OUTLET_NAME` (`OUTLET_NAME`),
  KEY `FK8D75F42D7A9D0766` (`PROVIDER_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=52 ;

CREATE TABLE IF NOT EXISTS `outlet_offer` (
  `OFFER_ID` bigint(20) NOT NULL,
  `OUTLET_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`OFFER_ID`,`OUTLET_ID`),
  KEY `FK3D4487AAC52C5CE6` (`OFFER_ID`),
  KEY `FK3D4487AABAA2082E` (`OUTLET_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `provider` (
  `PROVIDER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `EMAIL_ID` varchar(255) NOT NULL,
  `PROVIDER_NAME` varchar(255) NOT NULL,
  UNIQUE KEY `PROVIDER_ID` (`PROVIDER_ID`),
  UNIQUE KEY `EMAIL_ID` (`EMAIL_ID`),
  UNIQUE KEY `PROVIDER_NAME` (`PROVIDER_NAME`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=64 ;

ALTER TABLE `Coupons`
  ADD CONSTRAINT `FK9C50C4EDC52C5CE6` FOREIGN KEY (`OFFER_ID`) REFERENCES `Offer` (`OFFER_ID`);

ALTER TABLE `mail_attachments`
  ADD CONSTRAINT `FK95D55283138A864` FOREIGN KEY (`attachments_ATTACHMENT_ID`) REFERENCES `attachments` (`ATTACHMENT_ID`),
  ADD CONSTRAINT `FK95D55285FA67619` FOREIGN KEY (`mail_MAIL_ID`) REFERENCES `mail` (`MAIL_ID`);

ALTER TABLE `Offer`
  ADD CONSTRAINT `FK4892A3C7A9D0766` FOREIGN KEY (`PROVIDER_ID`) REFERENCES `provider` (`PROVIDER_ID`);

ALTER TABLE `offer_category`
  ADD CONSTRAINT `FK977DBB81752D8E0C` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `category` (`CATEGORY_ID`),
  ADD CONSTRAINT `FK977DBB81C52C5CE6` FOREIGN KEY (`OFFER_ID`) REFERENCES `Offer` (`OFFER_ID`);

ALTER TABLE `Outlet`
  ADD CONSTRAINT `FK8D75F42D7A9D0766` FOREIGN KEY (`PROVIDER_ID`) REFERENCES `provider` (`PROVIDER_ID`);

ALTER TABLE `outlet_offer`
  ADD CONSTRAINT `FK3D4487AABAA2082E` FOREIGN KEY (`OUTLET_ID`) REFERENCES `Outlet` (`OUTLET_ID`),
  ADD CONSTRAINT `FK3D4487AAC52C5CE6` FOREIGN KEY (`OFFER_ID`) REFERENCES `Offer` (`OFFER_ID`);
